spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_event
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.1.98
      port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
